<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ToiletSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('toilets')->insert([
            [
                'name' => 'Toilet Umum Pasar Johar',
                'address' => 'Jl. K.H. Agus Salim No.1, Semarang',
                'description' => 'Toilet bersih, tersedia sabun dan air mengalir.',
                'facilities' => json_encode(['Air Bersih', 'Sabun', 'Kloset Jongkok', 'Tempat Sampah']),
                'open' => '06:00',
                'close' => '21:00',
                'fee' => '2000',
                'photo' => null,
                'contact' => '08123456789',
                'access' => json_encode(['Ramah Difabel']),
                'latitude' => -6.9725,
                'longitude' => 110.4275,
                // => 4.0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Toilet Taman  Indonesia Kaya',
                'address' => 'Jl. Menteri Supeno, Semarang',
                'description' => 'Toilet umum di area taman, gratis dan bersih.',
                'facilities' => json_encode(['Air Bersih', 'Kloset Duduk', 'Tempat Sampah']),
                'open' => '05:00',
                'close' => '22:00',
                'fee' => 'Gratis',
                'photo' => null,
                'contact' => null,
                'access' => json_encode(['Toilet Anak']),
                'latitude' => -6.9935,
                'longitude' => 110.4201,
                // => 4.5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Toilet UNNES Gedung Rektorat',
                'address' => 'Kampus UNNES Sekaran, Gunungpati, Semarang',
                'description' => 'Toilet kampus, bersih dan terawat.',
                'facilities' => json_encode(['Air Bersih', 'Sabun', 'Kloset Duduk', 'Parkir']),
                'open' => '07:00',
                'close' => '17:00',
                'fee' => 'Gratis',
                'photo' => null,
                'contact' => '08567891234',
                'access' => json_encode(['Ramah Difabel', 'Toilet Pria/Wanita Terpisah']),
                'latitude' => -7.0490,
                'longitude' => 110.4250,
                // => 4.2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Toilet Stasiun Tawang',
                'address' => 'Jl. Tawang, Semarang',
                'description' => 'Toilet umum di stasiun, tersedia air dan sabun.',
                'facilities' => json_encode(['Air Bersih', 'Sabun', 'Kloset Duduk']),
                'open' => '00:00',
                'close' => '23:59',
                'fee' => '3000',
                'photo' => null,
                'contact' => '08121234567',
                'access' => json_encode(['Ramah Difabel']),
                'latitude' => -6.9632,
                'longitude' => 110.4281,
                // => 4.3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Toilet Mall Paragon',
                'address' => 'Jl. Pemuda No.118, Semarang',
                'description' => 'Toilet di dalam mall, bersih dan nyaman.',
                'facilities' => json_encode(['Air Bersih', 'Sabun', 'Kloset Duduk', 'Parkir']),
                'open' => '10:00',
                'close' => '22:00',
                'fee' => 'Gratis',
                'photo' => null,
                'contact' => null,
                'access' => json_encode(['Toilet Pria/Wanita Terpisah']),
                'latitude' => -6.9801,
                'longitude' => 110.4167,
                // => 4.7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Toilet SPBU Banyumanik',
                'address' => 'Jl. Setiabudi No. 192, Banyumanik, Semarang',
                'description' => 'Toilet SPBU, selalu tersedia air.',
                'facilities' => json_encode(['Air Bersih', 'Kloset Jongkok', 'Tempat Sampah']),
                'open' => '00:00',
                'close' => '23:59',
                'fee' => '2000',
                'photo' => null,
                'contact' => null,
                'access' => json_encode(['Ramah Difabel']),
                'latitude' => -7.0245,
                'longitude' => 110.4302,
                // => 4.1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Toilet Simpang Lima',
                'address' => 'Jl. Ahmad Yani, Semarang',
                'description' => 'Toilet umum di area Simpang Lima.',
                'facilities' => json_encode(['Air Bersih', 'Kloset Jongkok', 'Tempat Sampah']),
                'open' => '06:00',
                'close' => '22:00',
                'fee' => '2000',
                'photo' => null,
                'contact' => null,
                'access' => json_encode(['Toilet Anak']),
                'latitude' => -6.9930,
                'longitude' => 110.4200,
                // => 4.0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Toilet Terminal Terboyo',
                'address' => 'Jl. Terboyo, Semarang',
                'description' => 'Toilet di terminal bus, tersedia air dan sabun.',
                'facilities' => json_encode(['Air Bersih', 'Sabun', 'Kloset Jongkok']),
                'open' => '00:00',
                'close' => '23:59',
                'fee' => '2000',
                'photo' => null,
                'contact' => '08129876543',
                'access' => json_encode(['Ramah Difabel']),
                'latitude' => -6.9500,
                'longitude' => 110.4640,
                // => 4.4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Toilet Masjid Agung Jawa Tengah',
                'address' => 'Jl. Gajah Raya, Sambirejo, Semarang',
                'description' => 'Toilet luas, bersih, dan ramah difabel.',
                'facilities' => json_encode(['Air Bersih', 'Sabun', 'Kloset Duduk', 'Parkir']),
                'open' => '04:00',
                'close' => '22:00',
                'fee' => 'Gratis',
                'photo' => null,
                'contact' => null,
                'access' => json_encode(['Ramah Difabel', 'Toilet Pria/Wanita Terpisah']),
                'latitude' => -6.9845,
                'longitude' => 110.4497,
                // => 4.6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Toilet Lawang Sewu',
                'address' => 'Jl. Pemuda, Sekayu, Semarang',
                'description' => 'Toilet wisata, bersih dan terawat.',
                'facilities' => json_encode(['Air Bersih', 'Sabun', 'Kloset Duduk']),
                'open' => '07:00',
                'close' => '21:00',
                'fee' => '3000',
                'photo' => null,
                'contact' => null,
                'access' => json_encode(['Toilet Anak']),
                'latitude' => -6.9848,
                'longitude' => 110.4091,
                // => 4.5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Toilet RSUP Dr. Kariadi',
                'address' => 'Jl. Dr. Sutomo No.16, Semarang',
                'description' => 'Toilet rumah sakit, bersih dan selalu tersedia air.',
                'facilities' => json_encode(['Air Bersih', 'Sabun', 'Kloset Duduk', 'Tempat Sampah']),
                'open' => '00:00',
                'close' => '23:59',
                'fee' => 'Gratis',
                'photo' => null,
                'contact' => '0248311234',
                'access' => json_encode(['Ramah Difabel']),
                'latitude' => -6.9932,
                'longitude' => 110.4099,
                // => 4.8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Toilet Pasar Bulu',
                'address' => 'Jl. Mgr. Sugiyopranoto, Semarang',
                'description' => 'Toilet pasar tradisional, cukup bersih dan murah.',
                'facilities' => json_encode(['Air Bersih', 'Kloset Jongkok']),
                'open' => '05:00',
                'close' => '18:00',
                'fee' => '2000',
                'photo' => null,
                'contact' => null,
                'access' => json_encode(['Toilet Pria/Wanita Terpisah']),
                'latitude' => -6.9877,
                'longitude' => 110.4105,
                // => 3.9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Toilet Taman Srigunting',
                'address' => 'Jl. Letjen Suprapto, Kota Lama, Semarang',
                'description' => 'Toilet umum di taman kota, cocok untuk keluarga.',
                'facilities' => json_encode(['Air Bersih', 'Kloset Duduk', 'Tempat Sampah']),
                'open' => '06:00',
                'close' => '21:00',
                'fee' => '2000',
                'photo' => null,
                'contact' => null,
                'access' => json_encode(['Toilet Anak']),
                'latitude' => -6.9702,
                'longitude' => 110.4287,
                // => 4.2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Toilet Stasiun Poncol',
                'address' => 'Jl. Poncol, Semarang',
                'description' => 'Toilet di stasiun kereta, tersedia air dan sabun.',
                'facilities' => json_encode(['Air Bersih', 'Sabun', 'Kloset Jongkok']),
                'open' => '00:00',
                'close' => '23:59',
                'fee' => '3000',
                'photo' => null,
                'contact' => null,
                'access' => json_encode(['Ramah Difabel']),
                'latitude' => -6.9665,
                'longitude' => 110.4178,
                // => 4.0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Toilet Masjid Baiturrahman',
                'address' => 'Jl. Pandanaran, Semarang',
                'description' => 'Toilet masjid besar, bersih dan nyaman.',
                'facilities' => json_encode(['Air Bersih', 'Sabun', 'Kloset Duduk', 'Tempat Sampah']),
                'open' => '04:00',
                'close' => '22:00',
                'fee' => 'Gratis',
                'photo' => null,
                'contact' => null,
                'access' => json_encode(['Ramah Difabel']),
                'latitude' => -6.9870,
                'longitude' => 110.4150,
                // => 4.7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Toilet Museum Ronggowarsito',
                'address' => 'Jl. Abdul Rahman Saleh No.1, Semarang',
                'description' => 'Toilet museum, bersih dan terawat, cocok untuk pengunjung keluarga.',
                'facilities' => json_encode(['Air Bersih', 'Kloset Duduk', 'Tempat Sampah']),
                'open' => '08:00',
                'close' => '16:00',
                'fee' => '2000',
                'photo' => null,
                'contact' => null,
                'access' => json_encode(['Toilet Anak']),
                'latitude' => -6.9800,
                'longitude' => 110.3750,
                // => 4.3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Toilet Alun-Alun Semarang',
                'address' => 'Jl. Kauman, Semarang Tengah',
                'description' => 'Toilet umum di area alun-alun, ramai pengunjung dan selalu tersedia air.',
                'facilities' => json_encode(['Air Bersih', 'Kloset Jongkok', 'Tempat Sampah']),
                'open' => '05:00',
                'close' => '22:00',
                'fee' => '2000',
                'photo' => null,
                'contact' => null,
                'access' => json_encode(['Ramah Difabel']),
                'latitude' => -6.9720,
                'longitude' => 110.4205,
                // => 4.1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Toilet Taman Pandanaran',
                'address' => 'Jl. Pandanaran, Semarang Selatan',
                'description' => 'Toilet taman kota, bersih dan ramah anak.',
                'facilities' => json_encode(['Air Bersih', 'Kloset Duduk', 'Tempat Sampah']),
                'open' => '06:00',
                'close' => '20:00',
                'fee' => 'Gratis',
                'photo' => null,
                'contact' => null,
                'access' => json_encode(['Toilet Anak']),
                'latitude' => -6.9875,
                'longitude' => 110.4160,
                // => 4.4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Toilet Terminal Mangkang',
                'address' => 'Jl. Walisongo, Mangkang, Semarang',
                'description' => 'Toilet terminal bus, tersedia air dan sabun.',
                'facilities' => json_encode(['Air Bersih', 'Sabun', 'Kloset Jongkok']),
                'open' => '00:00',
                'close' => '23:59',
                'fee' => '3000',
                'photo' => null,
                'contact' => null,
                'access' => json_encode(['Ramah Difabel']),
                'latitude' => -6.9505,
                'longitude' => 110.3280,
                // => 4.0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Toilet Pasar Johar Lama',
                'address' => 'Jl. Agus Salim, Semarang',
                'description' => 'Toilet pasar tradisional, cukup bersih dan murah.',
                'facilities' => json_encode(['Air Bersih', 'Kloset Jongkok']),
                'open' => '05:00',
                'close' => '18:00',
                'fee' => '2000',
                'photo' => null,
                'contact' => null,
                'access' => json_encode(['Toilet Pria/Wanita Terpisah']),
                'latitude' => -6.9728,
                'longitude' => 110.4270,
                // => 3.8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Toilet Plaza Simpang Lima',
                'address' => 'Jl. Ahmad Yani No.1, Semarang',
                'description' => 'Toilet di pusat perbelanjaan, bersih dan nyaman.',
                'facilities' => json_encode(['Air Bersih', 'Sabun', 'Kloset Duduk', 'Tempat Sampah']),
                'open' => '10:00',
                'close' => '22:00',
                'fee' => 'Gratis',
                'photo' => null,
                'contact' => '0247654321',
                'access' => json_encode(['Toilet Pria/Wanita Terpisah']),
                'latitude' => -6.9938,
                'longitude' => 110.4208,
                // => 4.6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Toilet Rest Area Tol Banyumanik',
                'address' => 'Jl. Tol Banyumanik, Semarang',
                'description' => 'Toilet rest area, selalu tersedia air dan sabun.',
                'facilities' => json_encode(['Air Bersih', 'Sabun', 'Kloset Duduk', 'Kloset Jongkok']),
                'open' => '00:00',
                'close' => '23:59',
                'fee' => 'Gratis',
                'photo' => null,
                'contact' => null,
                'access' => json_encode(['Ramah Difabel']),
                'latitude' => -7.0321,
                'longitude' => 110.4389,
                // => 4.5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Toilet Pasar Peterongan',
                'address' => 'Jl. MT Haryono, Semarang',
                'description' => 'Toilet pasar, cukup bersih dan murah.',
                'facilities' => json_encode(['Air Bersih', 'Kloset Jongkok']),
                'open' => '05:00',
                'close' => '18:00',
                'fee' => '2000',
                'photo' => null,
                'contact' => null,
                'access' => json_encode(['Toilet Pria/Wanita Terpisah']),
                'latitude' => -7.0012,
                'longitude' => 110.4256,
                // => 3.7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Toilet Taman Diponegoro',
                'address' => 'Jl. Diponegoro, Semarang',
                'description' => 'Toilet taman kota, bersih dan ramah anak.',
                'facilities' => json_encode(['Air Bersih', 'Kloset Duduk', 'Tempat Sampah']),
                'open' => '06:00',
                'close' => '20:00',
                'fee' => 'Gratis',
                'photo' => null,
                'contact' => null,
                'access' => json_encode(['Toilet Anak']),
                'latitude' => -6.9911,
                'longitude' => 110.4142,
                // => 4.2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Toilet Stasiun Brumbung',
                'address' => 'Jl. Brumbung Raya, Semarang',
                'description' => 'Toilet di stasiun kereta, tersedia air dan sabun.',
                'facilities' => json_encode(['Air Bersih', 'Sabun', 'Kloset Jongkok']),
                'open' => '00:00',
                'close' => '23:59',
                'fee' => '3000',
                'photo' => null,
                'contact' => null,
                'access' => json_encode(['Ramah Difabel']),
                'latitude' => -7.0132,
                'longitude' => 110.4951,
                // => 4.0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Toilet Masjid Raya Baiturrahman',
                'address' => 'Jl. Pandanaran No.126, Semarang',
                'description' => 'Toilet masjid raya, bersih dan luas.',
                'facilities' => json_encode(['Air Bersih', 'Sabun', 'Kloset Duduk', 'Tempat Sampah']),
                'open' => '04:00',
                'close' => '22:00',
                'fee' => 'Gratis',
                'photo' => null,
                'contact' => null,
                'access' => json_encode(['Ramah Difabel']),
                'latitude' => -6.9872,
                'longitude' => 110.4148,
                // => 4.8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Toilet Pasar Karangayu',
                'address' => 'Jl. Jend. Sudirman, Semarang',
                'description' => 'Toilet pasar tradisional, cukup bersih.',
                'facilities' => json_encode(['Air Bersih', 'Kloset Jongkok']),
                'open' => '05:00',
                'close' => '18:00',
                'fee' => '2000',
                'photo' => null,
                'contact' => null,
                'access' => json_encode(['Toilet Pria/Wanita Terpisah']),
                'latitude' => -6.9785,
                'longitude' => 110.3932,
                // => 3.9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Toilet Taman KB',
                'address' => 'Jl. Menteri Supeno, Semarang',
                'description' => 'Toilet taman kota, bersih dan nyaman.',
                'facilities' => json_encode(['Air Bersih', 'Kloset Duduk', 'Tempat Sampah']),
                'open' => '06:00',
                'close' => '20:00',
                'fee' => 'Gratis',
                'photo' => null,
                'contact' => null,
                'access' => json_encode(['Toilet Anak']),
                'latitude' => -6.9937,
                'longitude' => 110.4203,
                // => 4.3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Toilet SPBU Majapahit',
                'address' => 'Jl. Majapahit No. 222, Semarang',
                'description' => 'Toilet SPBU, selalu tersedia air dan sabun.',
                'facilities' => json_encode(['Air Bersih', 'Sabun', 'Kloset Jongkok']),
                'open' => '00:00',
                'close' => '23:59',
                'fee' => '2000',
                'photo' => null,
                'contact' => null,
                'access' => json_encode(['Ramah Difabel']),
                'latitude' => -7.0088,
                'longitude' => 110.4542,
                // => 4.1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Toilet Terminal Penggaron',
                'address' => 'Jl. Penggaron, Semarang',
                'description' => 'Toilet terminal bus, tersedia air dan sabun.',
                'facilities' => json_encode(['Air Bersih', 'Sabun', 'Kloset Jongkok']),
                'open' => '00:00',
                'close' => '23:59',
                'fee' => '2000',
                'photo' => null,
                'contact' => null,
                'access' => json_encode(['Ramah Difabel']),
                'latitude' => -7.0291,
                'longitude' => 110.4785,
                // => 4.2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Toilet Pasar Gayamsari',
                'address' => 'Jl. Dr. Cipto, Semarang',
                'description' => 'Toilet pasar, cukup bersih dan murah.',
                'facilities' => json_encode(['Air Bersih', 'Kloset Jongkok']),
                'open' => '05:00',
                'close' => '18:00',
                'fee' => '2000',
                'photo' => null,
                'contact' => null,
                'access' => json_encode(['Toilet Pria/Wanita Terpisah']),
                'latitude' => -7.0080,
                'longitude' => 110.4450,
                // => 3.8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
